pull_request_rules:
  - name: assign and label eikek-scala-steward's PRs
    conditions:
      - author=eikek-scala-steward[bot]
    actions:
      assign:
        users: [eikek]
      label:
        add: ["type: dependencies"]
  - name: label eikek-scala-steward's breaking PRs
    conditions:
      - author=eikek-scala-steward[bot]
      - "body~=(labels: library-update, early-semver-major)|(labels: sbt-plugin-update, early-semver-major)"
    actions:
      label:
        add: ["type: breaking"]
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=eikek-scala-steward[bot]
      - base=master
      - status-success=ci
    actions:
      merge:
        method: squash
  - name: automatic update for dependency update PRs
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - "label=type: dependencies"
    actions:
      update: {}
